apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ctscan
spec:
  selector:
    matchLabels:
      app: ctscan
  replicas: 1
  template:
    metadata:
      labels:
        app: ctscan
    spec:
      containers:
      - name: ctscan
        image: prabhu25/my-bank-service:@@{tag}
        ports:
        - containerPort: 80
