apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: ctsops
spec:
  selector:
    matchLabels:
      app: ctsops
  replicas: 1
  template:
    metadata:
      labels:
        app: ctsops
    spec:
      containers:
      - name: ctsops
        image: prabhu25/my-bank-service:@@{tag}
        ports:
        - containerPort: 80
